spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/gulimall_pms?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 192.168.56.10
    port: 6379
  application:
    name: gulimall-product
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1


server:
  port: 10001
logging:
  level:
    com.atguigu.gulimall: debug


